# ===================================================================
# springboot配置
# ===================================================================
spring:
  application:
    name: @project.name@
  profiles:
    active: @activatedYml@

server:
  port: 21001
  servlet:
    context-path: /

logging:
  path: @project.name@_log
